import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggleDropdown } from "@/components/theme-switcher";
import Providers from "@/components/providers";
import RainbowKitConnectButton from "@/components/ui/connect-button";
import { Wrench } from "lucide-react";
import { Toaster } from "@/components/ui/sonner";
import Link from "next/link";
import { MonadPadIcon } from "@/components/icons";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`antialiased`}>
				<Providers>
					<div className="relative z-[100]">
						<div className="flex justify-between items-center gap-2 w-full px-4 py-3">
							<Link href="/" className="flex items-center gap-1.5">
								<Wrench size={20} />
								<p className="text-base font-bold hidden sm:block">Monad Tools</p>
							</Link>
							<div className="flex items-center gap-2">
								<ModeToggleDropdown />
								<RainbowKitConnectButton />
							</div>
						</div>
					</div>
					<div className="lg:-mt-[60px]">{children}</div>
					<div className="bg-black/25 py-8 px-6">
						<div className="flex flex-wrap gap-6 md:gap-2 mx-auto justify-between items-center">
							<div className="flex flex-wrap items-center gap-1 text-sm text-muted-foreground font-medium">
								<p className="">Monad Tools is a community project made by</p>
								<Link href="https://monadpad.xyz" target="_blank" className="text-primary underline flex items-center gap-1"><MonadPadIcon className="size-4" />Monad Pad</Link>
							</div>
							<p className="text-sm text-muted-foreground font-medium">We are not affiliated with Monad</p>
						</div>
					</div>
					<Toaster expand />
				</Providers>
			</body>
		</html>
	);
}
